### ISSUE TITLE
Add QR-Code to Preview Deploys

### ISSUE THREAD

**Issue by LukaHarambasic** [workeffortwaste/netlify-quick-qr#1]
Hi,

thank's for this nice chrome extension!

I just added for myself in a hacky way the qr codes to the deploy previews. Would you be interested that I create a PR? If yes I would work on the styling and the code style which is currently quite ugly on my side :)

![image](https://user-images.githubusercontent.com/22857823/96926259-a54f3600-14b5-11eb-8063-3c4a4e21bad1.png)

Cheers,
Luka

**Comment by workeffortwaste** [comment]
This is a great addition. If you wanted to make a PR I'd be happy to add it!

**Comment by workeffortwaste** [comment]
This is implemented in v0.2.0
